[build]
builder = "nixpacks"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "cd frontend && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
